apiVersion: v1
kind: ReplicationController
metadata:
  name: webrc
spec:
  replicas: 5
  template:
    metadata:
      name: nginx
      labels:
        project: robochef
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
